on: push
name: TOC Generator
permissions:
  contents: write  # This grants write access to push changes
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          COMMIT_MESSAGE: "docs action: update table of contents"
          MAX_HEADER_LEVEL: 2
